[package]
name = "key-finder"
version = "1.0.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = "0.10"

[dev-dependencies]
actix-rt = "2.2"
